### ISSUE TITLE
请求增加撤销按钮或者以拉黑时间顺序显示屏蔽列表

### ISSUE THREAD

**Issue by wandero** [toumasuxp/Personal_Blocklist#1]
但误操作之后撤销很麻烦，甚至无法分辨误操作的域名
能否增加一个撤销按钮或者拉黑时间顺序显示屏蔽列表
扩展很好用，非常感谢

**Comment by toumasuxp** [comment]
Thanks for your issue!
I fixed that the URL Clicked by mistake can be undone.

Below is an example.
I will fix the details of the UI later

![personalblocklistgif](https://user-images.githubusercontent.com/33715405/78857873-a236b000-7a65-11ea-9b1e-3145c2bf3c2a.gif)

**Comment by wandero** [comment]
Thanks a lot
